// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleBrands.Infrastructure.Data;

#nullable disable

namespace VehicleBrands.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210210432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleBrands.Domain.Entities.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Headquarters")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsLuxury")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MarcasAutos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "Japan",
                            FoundedYear = 1937,
                            Headquarters = "Toyota City, Aichi",
                            IsLuxury = false,
                            Name = "Toyota",
                            Website = "https://www.toyota.com"
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "United States",
                            FoundedYear = 1903,
                            Headquarters = "Dearborn, Michigan",
                            IsLuxury = false,
                            Name = "Ford",
                            Website = "https://www.ford.com"
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "Germany",
                            FoundedYear = 1916,
                            Headquarters = "Munich, Bavaria",
                            IsLuxury = true,
                            Name = "BMW",
                            Website = "https://www.bmw.com"
                        },
                        new
                        {
                            Id = 4,
                            CountryOfOrigin = "Italy",
                            FoundedYear = 1947,
                            Headquarters = "Maranello, Modena",
                            IsLuxury = true,
                            Name = "Ferrari",
                            Website = "https://www.ferrari.com"
                        },
                        new
                        {
                            Id = 5,
                            CountryOfOrigin = "South Korea",
                            FoundedYear = 1967,
                            Headquarters = "Seoul",
                            IsLuxury = false,
                            Name = "Hyundai",
                            Website = "https://www.hyundai.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
